export const courseDatabase = [
	{
		course_name: 'Introduction to Programming',
		prefix: 'COP',
		course_number: 1010,
		CRN: 10101,
		capacity: 50,
		enrolled: 45,
		overridable: true,
		waitlisted: 2,
		instructor: 'Dr. Alice Smith',
		credits: 3,
		grade: 'A'
	},
	{
		course_name: 'Data Structures',
		prefix: 'COP',
		course_number: 2020,
		CRN: 10202,
		capacity: 60,
		enrolled: 60,
		overridable: false,
		waitlisted: 5,
		instructor: 'Dr. Bob Johnson',
		credits: 3,
		grade: 'B+'
	},
	{
		course_name: 'Algorithms',
		prefix: 'COP',
		course_number: 3030,
		CRN: 10303,
		capacity: 40,
		enrolled: 38,
		overridable: true,
		waitlisted: 0,
		instructor: 'Dr. Carol Davis',
		credits: 3,
		grade: 'A-'
	},
	{
		course_name: 'Operating Systems',
		prefix: 'COP',
		course_number: 4040,
		CRN: 10404,
		capacity: 35,
		enrolled: 33,
		overridable: false,
		waitlisted: 3,
		instructor: 'Dr. Daniel Lee',
		credits: 4,
		grade: 'B'
	},
	{
		course_name: 'Databases',
		prefix: 'COP',
		course_number: 5050,
		CRN: 20101,
		capacity: 30,
		enrolled: 25,
		overridable: true,
		waitlisted: 0,
		instructor: 'Dr. Emma Brown',
		credits: 3,
		grade: null // Current enrollment, no grade yet
	},
	{
		course_name: 'Machine Learning',
		prefix: 'COP',
		course_number: 6060,
		CRN: 20202,
		capacity: 40,
		enrolled: 40,
		overridable: false,
		waitlisted: 4,
		instructor: 'Dr. Frank Miller',
		credits: 3,
		grade: null // Current enrollment, no grade yet
	},
	{
		course_name: 'Artificial Intelligence',
		prefix: 'COP',
		course_number: 7070,
		CRN: 20303,
		capacity: 25,
		enrolled: 20,
		overridable: true,
		waitlisted: 1,
		instructor: 'Dr. Grace Wilson',
		credits: 4,
		grade: null // Current enrollment, no grade yet
	},
	// Extra courses
	{
		course_name: 'Web Development',
		prefix: 'COP',
		course_number: 8080,
		CRN: 30101,
		capacity: 45,
		enrolled: 40,
		overridable: true,
		waitlisted: 2,
		instructor: 'Dr. Hannah Thomas',
		credits: 3,
		grade: null
	},
	{
		course_name: 'Cloud Computing',
		prefix: 'COP',
		course_number: 9090,
		CRN: 30202,
		capacity: 30,
		enrolled: 28,
		overridable: false,
		waitlisted: 3,
		instructor: 'Dr. Ian Taylor',
		credits: 3,
		grade: null
	}
];
